"""initial 13 tables

Revision ID: f532646fe643
Revises:
Create Date: 2026-08-16 14:38:33.347816

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

revision: str = "f532646fe643"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("operator_user_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=120), nullable=True),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("client_ip", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=6), nullable=False),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_operator_created", "audit_logs", ["operator_user_id", "created_at"], unique=False
    )
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("jti_hash", sa.String(length=64), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=6), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=6), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=6), nullable=True),
        sa.Column("client_ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=6), nullable=False),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti_hash"),
    )
    op.create_index(
        "ix_auth_sessions_user_expires", "auth_sessions", ["user_id", "expires_at"], unique=False
    )
    op.create_table(
        "chat_messages",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("seq_no", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("answer_source", sa.String(length=20), nullable=True),
        sa.Column("rag_trace_id", sa.String(length=120), nullable=True),
        sa.Column("terminal_reason_code", sa.String(length=100), nullable=True),
        sa.Column("citations_json", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=6), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=6), nullable=True),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_cm_rag_trace_id", "chat_messages", ["rag_trace_id"], unique=False)
    op.create_index("ix_cm_session_seq", "chat_messages", ["session_id", "seq_no"], unique=True)
    op.create_index("ix_cm_turn_id", "chat_messages", ["turn_id"], unique=False)
    op.create_table(
        "chat_sessions",
        sa.Column("channel", sa.String(length=24), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("external_subject_hash", sa.String(length=64), nullable=True),
        sa.Column("external_session_id", sa.String(length=120), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=6), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=6), nullable=True),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=6), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=6), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document_replacements",
        sa.Column("old_managed_document_id", sa.String(length=36), nullable=False),
        sa.Column("new_managed_document_id", sa.String(length=36), nullable=False),
        sa.Column("replacement_task_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=6), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=6), nullable=True),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "faq_candidates",
        sa.Column("knowledge_scope", sa.String(length=32), nullable=False),
        sa.Column("normalized_question", sa.Text(), nullable=False),
        sa.Column("normalized_question_hash", sa.String(length=64), nullable=False),
        sa.Column("sample_questions_json", sa.JSON(), nullable=False),
        sa.Column("ask_count", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("suggested_answer", sa.Text(), nullable=True),
        sa.Column("source_log_ids_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("published_faq_id", sa.String(length=36), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=6), nullable=False),
        sa.Column("reviewed_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=6), nullable=True),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "faq_sync_runs",
        sa.Column("knowledge_scope", sa.String(length=32), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("generated_file_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("rag_task_id", sa.String(length=120), nullable=True),
        sa.Column("rag_document_id", sa.String(length=120), nullable=True),
        sa.Column("previous_rag_document_id", sa.String(length=120), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("requested_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=6), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=6), nullable=True),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "faqs",
        sa.Column("knowledge_scope", sa.String(length=32), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("normalized_question", sa.Text(), nullable=False),
        sa.Column("normalized_question_hash", sa.String(length=64), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source_candidate_id", sa.String(length=36), nullable=True),
        sa.Column("hit_count", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("rag_sync_status", sa.String(length=20), nullable=False),
        sa.Column("rag_sync_error", sa.String(length=1000), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("reviewed_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=6), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=6), nullable=False),
        sa.Column("unpublished_at", sa.DateTime(timezone=6), nullable=True),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_faqs_scope_hash", "faqs", ["knowledge_scope", "normalized_question_hash"], unique=True
    )
    op.create_index("ix_faqs_scope_status", "faqs", ["knowledge_scope", "status"], unique=False)
    op.create_table(
        "knowledge_gap_candidates",
        sa.Column("knowledge_scope", sa.String(length=32), nullable=False),
        sa.Column("normalized_question", sa.Text(), nullable=False),
        sa.Column("normalized_question_hash", sa.String(length=64), nullable=False),
        sa.Column("sample_questions_json", sa.JSON(), nullable=False),
        sa.Column("source_log_ids_json", sa.JSON(), nullable=False),
        sa.Column("ask_count", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("reason_code", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("resolution_note", sa.String(length=1000), nullable=True),
        sa.Column("resolved_document_id", sa.String(length=36), nullable=True),
        sa.Column("reviewed_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=6), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=6), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=6), nullable=True),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_kgc_scope_hash",
        "knowledge_gap_candidates",
        ["knowledge_scope", "normalized_question_hash"],
        unique=True,
    )
    op.create_table(
        "managed_documents",
        sa.Column("rag_document_id", sa.String(length=120), nullable=False),
        sa.Column("rag_dataset_id", sa.String(length=120), nullable=False),
        sa.Column("knowledge_scope", sa.String(length=32), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("index_version", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("rag_status", sa.String(length=40), nullable=False),
        sa.Column("rag_parse_status", sa.String(length=40), nullable=True),
        sa.Column("rag_index_status", sa.String(length=40), nullable=True),
        sa.Column("platform_status", sa.String(length=32), nullable=False),
        sa.Column("chunk_count", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("latest_rag_task_id", sa.String(length=120), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=6), nullable=True),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=6), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=6), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rag_document_id"),
    )
    op.create_index(
        "ix_md_dataset_rag_status",
        "managed_documents",
        ["rag_dataset_id", "rag_status"],
        unique=False,
    )
    op.create_index(
        "ix_md_scope_status_updated",
        "managed_documents",
        ["knowledge_scope", "platform_status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "qa_access_logs",
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("channel", sa.String(length=24), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("external_subject_hash", sa.String(length=64), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("normalized_question", sa.Text(), nullable=False),
        sa.Column("normalized_question_hash", sa.String(length=64), nullable=False),
        sa.Column("allowed_scopes_json", sa.JSON(), nullable=False),
        sa.Column("answer_source", sa.String(length=20), nullable=False),
        sa.Column("faq_id", sa.String(length=36), nullable=True),
        sa.Column("rag_trace_id", sa.String(length=120), nullable=True),
        sa.Column("terminal_reason_code", sa.String(length=100), nullable=True),
        sa.Column("citation_count", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("citation_document_ids_json", sa.JSON(), nullable=False),
        sa.Column("input_tokens", mysql.INTEGER(unsigned=True), nullable=True),
        sa.Column("output_tokens", mysql.INTEGER(unsigned=True), nullable=True),
        sa.Column("total_tokens", mysql.INTEGER(unsigned=True), nullable=True),
        sa.Column("latency_ms", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=6), nullable=False),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_qa_channel_created", "qa_access_logs", ["channel", "created_at"], unique=False
    )
    op.create_index(
        "ix_qa_hash_created",
        "qa_access_logs",
        ["normalized_question_hash", "created_at"],
        unique=False,
    )
    op.create_index("ix_qa_rag_trace_id", "qa_access_logs", ["rag_trace_id"], unique=False)
    op.create_index("ix_qa_turn_id", "qa_access_logs", ["turn_id"], unique=True)
    op.create_table(
        "rag_integration_tasks",
        sa.Column("operation", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("managed_document_id", sa.String(length=36), nullable=True),
        sa.Column("rag_task_id", sa.String(length=120), nullable=True),
        sa.Column("rag_document_id", sa.String(length=120), nullable=True),
        sa.Column("rag_dataset_id", sa.String(length=120), nullable=False),
        sa.Column("rag_status", sa.String(length=40), nullable=True),
        sa.Column("done_nodes_json", sa.JSON(), nullable=False),
        sa.Column("running_nodes_json", sa.JSON(), nullable=False),
        sa.Column("failed_node", sa.String(length=120), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("requested_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=6), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=6), nullable=True),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=6), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=6), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rag_task_id"),
    )
    op.create_index(
        "ix_rit_status_updated", "rag_integration_tasks", ["status", "updated_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=6), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=6), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=6), nullable=True),
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=6), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=6), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index("ix_users_status_role", "users", ["status", "role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_status_role", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_rit_status_updated", table_name="rag_integration_tasks")
    op.drop_table("rag_integration_tasks")
    op.drop_index("ix_qa_turn_id", table_name="qa_access_logs")
    op.drop_index("ix_qa_rag_trace_id", table_name="qa_access_logs")
    op.drop_index("ix_qa_hash_created", table_name="qa_access_logs")
    op.drop_index("ix_qa_channel_created", table_name="qa_access_logs")
    op.drop_table("qa_access_logs")
    op.drop_index("ix_md_scope_status_updated", table_name="managed_documents")
    op.drop_index("ix_md_dataset_rag_status", table_name="managed_documents")
    op.drop_table("managed_documents")
    op.drop_index("ix_kgc_scope_hash", table_name="knowledge_gap_candidates")
    op.drop_table("knowledge_gap_candidates")
    op.drop_index("ix_faqs_scope_status", table_name="faqs")
    op.drop_index("ix_faqs_scope_hash", table_name="faqs")
    op.drop_table("faqs")
    op.drop_table("faq_sync_runs")
    op.drop_table("faq_candidates")
    op.drop_table("document_replacements")
    op.drop_table("chat_sessions")
    op.drop_index("ix_cm_turn_id", table_name="chat_messages")
    op.drop_index("ix_cm_session_seq", table_name="chat_messages")
    op.drop_index("ix_cm_rag_trace_id", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index("ix_auth_sessions_user_expires", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index("ix_audit_operator_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
